# Generated by Django 4.1 on 2022-08-25 09:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mamlakatni kiriting:', max_length=100, verbose_name='mamlakat')),
            ],
            options={
                'verbose_name': 'mamlakat',
                'verbose_name_plural': 'mamlakatlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Viloyatni kiriting:', max_length=100, verbose_name='viloyat')),
            ],
            options={
                'verbose_name': 'viloyat',
                'verbose_name_plural': 'viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Shaxs sur'atini yuklang:", upload_to='unkimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Shaxs ismini kiriting:', max_length=100, verbose_name='ismi')),
                ('last_name', models.CharField(help_text='Shaxs familiyasini kiriting:', max_length=100, verbose_name='familiya')),
                ('age', models.PositiveIntegerField(help_text='Shaxs yoshini kiriting:', verbose_name='yoshi')),
                ('image', models.ImageField(help_text="Shaxs sur'atini yuklang:", upload_to='images/', verbose_name="sur'at")),
                ('discription', ckeditor.fields.RichTextField(help_text="to'liq izoh kiritng:", verbose_name="to'liq ma'lumot")),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.country', verbose_name='mamlakat')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.region', verbose_name='viloyat')),
            ],
            options={
                'verbose_name': 'shaxs',
                'verbose_name_plural': 'shaxslar',
            },
        ),
    ]
